name: Probot Entomologist
description: Probot App to triage bug reports
url: https://github.com/lorinkoz/entomologist.git
default_events:
  - issue_comment
  - issues
  - label
default_permissions:
  issues: write
  metadata: read
