name: Probot Ladybug
description: Probot App to triage issues
url: https://github.com/lorinkoz/probot-ladybug.git
default_events:
  - issue_comment
  - issues
  - label
default_permissions:
  issues: write
  metadata: read
